debug: true
enable_http: true
enable_grpc: false
pprof_addr: ":5060"
http_addr: ":5050"
grpc_addr: ":5040"
jwt_pem: E:\\Tools\\openssl\\setup\\erp\\dev\\private.pem

transfer_encrypt:
  public_key: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDMGVDa3N4dkdtUTdjZ0lOZUNLN1Z0aklDUgovanlTRTNJM3dTUW5HQVFHVEVOUnhMa01tSjNhdzdXdXRHUTVXd1NJQ1ZCNWlKZHo4Y3Q4bTJ1S1M1eVVMOFg0CkM4RGd6TmxhaFIzOVlGMWFVUlpFMGRBMzAra2ltQy93M1J6dUtmbFZxMHdBcU5EbXk3di9rWXBRNDF0LzFjTDkKNWhuV2FUWitrdXVDSFM0Ui9RSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ=="
  private_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWFFJQkFBS0JnUUMwZUNrc3h2R21RN2NnSU5lQ0s3VnRqSUNSL2p5U0UzSTN3U1FuR0FRR1RFTlJ4TGtNCm1KM2F3N1d1dEdRNVd3U0lDVkI1aUpkejhjdDhtMnVLUzV5VUw4WDRDOERnek5sYWhSMzlZRjFhVVJaRTBkQTMKMCtraW1DL3czUnp1S2ZsVnEwd0FxTkRteTd2L2tZcFE0MXQvMWNMOTVobldhVFora3V1Q0hTNFIvUUlEQVFBQgpBb0dBTHo5K1dEREZ0MmZuRzh3OVgrRWRvTTYySW9MVFROTTJoZzVVN3I5RTNuazg3cjE0VFNudnVnU2ZIbHd3CkdTd1JKYVI2b3piMW4rOWYvUUdieUJzL3BNT3UwNjh5NUZHdTBSaHVVMDVxMHNXbTdiTFoxTHQwdThSNlVzU24KK3Ewa2lUUXhlT3dweWp0YXlBNmFiSEh6eUQrN2RXSlhMbHM2Y1NVS0R3MDE1cWtDUVFEZ1JWVE4xQWRaNjhRRQpCL2JxaExSRU8wVlVrZitHS29VTHVjdG5WbG4yVFRmZVE4Y1Y0cVJ2VE05YlU3RWlwUjFPL3BPRG04WTdKRVJoCnZoWnBoRjViQWtFQXpnQnNYWHpXQ2QrTkpVYXJPamt4c2gyVTErQUZNcWhXRjhqWVZvMDB1ZGlhWnpUMy9Zb2IKK0NmZzl4QnByVEdJWnFuWFRnc2JvZTNnVWlJTTJiSHdod0pCQUlIV0FZdUxwWm5jVVVXWUtzMkllQ2hNUEE0QwoyL0NiYXh6bnVpY2dLY0xhMzI0d3hQQVpudUxFa0FNcVI1RnNEN1NzMDAvTS9nMDlLTTJCVTg1UWtLTUNRRzRyClNja0JuMUp1YlFUWGMzRlM3eUhyc2hOMWFqSTZWcmlub0JOQnQwWUE4aXBwNklwK2x4Q3kreHdHZWcyMjVOVEsKMWl1Vnd6UnBqRU5BbEpERUdmY0NRUUM5dmNoOENPWGx4c0JtRmJ4WXBkWmRWV21KOWc5RjB0WE9WdkRlendsNQo2Y0JDdUhQSnlEVitkaUIvQXMrYm1oUWw4bUF0aDZ0SU1OZUVqWHhHYUkzNwotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ=="

redis:
  addr: 192.168.43.188:6379
  user: ""
  passwd: ""

db_dsn: root:123456@tcp(127.0.0.1:3306)/erp?charset=utf8mb4&parseTime=True&loc=Local
asset_dir: C:\\x\\erp\\asset\\upload
