package app

// struct field
const (
	FieldPayAt        = "PayAt"
	FieldPassword     = "Password"
	FieldIsHidden     = "IsHidden"
	FieldMenuId       = "MenuId"
	FieldUuid         = "Uuid"
	FieldName         = "Name"
	FieldStatus       = "Status"
	FieldIsCreator    = "IsCreator"
	FieldComponent    = "Component"
	FieldInitialMoney = "InitialMoney"
	FieldCreatedAt    = "CreatedAt"
	FieldDeletedAt    = "DeletedAt"
	FieldRoleList     = "RoleList"
	FieldHandleBy     = "HandleBy"
	FieldMenuList     = "MenuList"
	FieldUserId       = "UserId"
	FieldMark         = "Mark"
	FieldId           = "Id"
	FieldTicket       = "Ticket"
	FieldAttachment   = "Attachment"
	FieldSort         = "Sort"
	FieldCategory     = "Category"
	FieldRoleId       = "RoleId"
	FieldAccountId    = "AccountId"
	FieldUpdatedAt    = "UpdatedAt"
	FieldNickName     = "NickName"
	FieldParentId     = "ParentId"
	FieldType         = "Type"
	FieldIcon         = "Icon"
	FieldPath         = "Path"
	FieldRedirect     = "Redirect"
)

// db field
const (
	dbPayAt        = "pay_at"
	dbPassword     = "password"
	dbIsHidden     = "is_hidden"
	dbMenuId       = "menu_id"
	dbUuid         = "uuid"
	dbName         = "name"
	dbStatus       = "status"
	dbIsCreator    = "is_creator"
	dbComponent    = "component"
	dbInitialMoney = "initial_money"
	dbCreatedAt    = "created_at"
	dbDeletedAt    = "deleted_at"
	dbRoleList     = "role_list"
	dbHandleBy     = "handle_by"
	dbMenuList     = "menu_list"
	dbUserId       = "user_id"
	dbMark         = "mark"
	dbId           = "id"
	dbTicket       = "ticket"
	dbAttachment   = "attachment"
	dbSort         = "sort"
	dbCategory     = "category"
	dbRoleId       = "role_id"
	dbAccountId    = "account_id"
	dbUpdatedAt    = "updated_at"
	dbNickName     = "nick_name"
	dbParentId     = "parent_id"
	dbType         = "type"
	dbIcon         = "icon"
	dbPath         = "path"
	dbRedirect     = "redirect"
)
