package app

// struct field
const (
	FieldUserId = "UserId"
	FieldMenuId = "MenuId"
	FieldPayAt = "PayAt"
	FieldCategory = "Category"
	FieldPayMoney = "PayMoney"
	FieldAccountId = "AccountId"
	FieldName = "Name"
	FieldParentId = "ParentId"
	FieldUuid = "Uuid"
	FieldAttachment = "Attachment"
	FieldCreatedAt = "CreatedAt"
	FieldMenuList = "MenuList"
	FieldTicket = "Ticket"
	FieldPassword = "Password"
	FieldComponent = "Component"
	FieldIcon = "Icon"
	FieldType = "Type"
	FieldRoleList = "RoleList"
	FieldIsCreator = "IsCreator"
	FieldIsHidden = "IsHidden"
	FieldRoleId = "RoleId"
	FieldInitialMoney = "InitialMoney"
	FieldDeletedAt = "DeletedAt"
	FieldStatus = "Status"
	FieldRedirect = "Redirect"
	FieldMark = "Mark"
	FieldHandleBy = "HandleBy"
	FieldId = "Id"
	FieldUpdatedAt = "UpdatedAt"
	FieldSort = "Sort"
	FieldNickName = "NickName"
	FieldPath = "Path"
)

// db field
const (
	dbUserId = "user_id"
	dbMenuId = "menu_id"
	dbPayAt = "pay_at"
	dbCategory = "category"
	dbPayMoney = "pay_money"
	dbAccountId = "account_id"
	dbName = "name"
	dbParentId = "parent_id"
	dbUuid = "uuid"
	dbAttachment = "attachment"
	dbCreatedAt = "created_at"
	dbMenuList = "menu_list"
	dbTicket = "ticket"
	dbPassword = "password"
	dbComponent = "component"
	dbIcon = "icon"
	dbType = "type"
	dbRoleList = "role_list"
	dbIsCreator = "is_creator"
	dbIsHidden = "is_hidden"
	dbRoleId = "role_id"
	dbInitialMoney = "initial_money"
	dbDeletedAt = "deleted_at"
	dbStatus = "status"
	dbRedirect = "redirect"
	dbMark = "mark"
	dbHandleBy = "handle_by"
	dbId = "id"
	dbUpdatedAt = "updated_at"
	dbSort = "sort"
	dbNickName = "nick_name"
	dbPath = "path"
)