package app

// struct field
const (
	FieldDeletedAt    = "DeletedAt"
	FieldRoleList     = "RoleList"
	FieldPath         = "Path"
	FieldType         = "Type"
	FieldUpdatedAt    = "UpdatedAt"
	FieldRedirect     = "Redirect"
	FieldUserId       = "UserId"
	FieldNickName     = "NickName"
	FieldIcon         = "Icon"
	FieldIsHidden     = "IsHidden"
	FieldRoleId       = "RoleId"
	FieldCreatedAt    = "CreatedAt"
	FieldName         = "Name"
	FieldPassword     = "Password"
	FieldStatus       = "Status"
	FieldMenuList     = "MenuList"
	FieldComponent    = "Component"
	FieldSort         = "Sort"
	FieldMenuId       = "MenuId"
	FieldId           = "Id"
	FieldInitialMoney = "InitialMoney"
	FieldIsCreator    = "IsCreator"
)

// db field
const (
	dbDeletedAt    = "deleted_at"
	dbRoleList     = "role_list"
	dbPath         = "path"
	dbType         = "type"
	dbUpdatedAt    = "updated_at"
	dbRedirect     = "redirect"
	dbUserId       = "user_id"
	dbNickName     = "nick_name"
	dbIcon         = "icon"
	dbIsHidden     = "is_hidden"
	dbRoleId       = "role_id"
	dbCreatedAt    = "created_at"
	dbName         = "name"
	dbPassword     = "password"
	dbStatus       = "status"
	dbMenuList     = "menu_list"
	dbComponent    = "component"
	dbSort         = "sort"
	dbMenuId       = "menu_id"
	dbId           = "id"
	dbInitialMoney = "initial_money"
	dbIsCreator    = "is_creator"
)
