// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.3
// source: erp.proto

package erp

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	listoption "github.com/ml444/gkit/listoption"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// range of error codes: [1, 2147483648]
type ErrCode int32

const (
	ErrCode_Success ErrCode = 0
	// @status_code: 400
	ErrCode_ErrInvalidParam ErrCode = 1 // 非法参数
	// @status_code: 400
	ErrCode_ErrParamRequired ErrCode = 2 // 缺失参数
	// @status_code: 404
	ErrCode_ErrNotFoundErp ErrCode = 3 // 未找到相关记录
	// @status_code: 404
	ErrCode_ErrNotFoundRole ErrCode = 4 // 未找到相关记录
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "Success",
		1: "ErrInvalidParam",
		2: "ErrParamRequired",
		3: "ErrNotFoundErp",
		4: "ErrNotFoundRole",
	}
	ErrCode_value = map[string]int32{
		"Success":          0,
		"ErrInvalidParam":  1,
		"ErrParamRequired": 2,
		"ErrNotFoundErp":   3,
		"ErrNotFoundRole":  4,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_erp_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_erp_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{0}
}

type ListErpReq_ListOpt int32

const (
	ListErpReq_ListOptNil ListErpReq_ListOpt = 0
	// @valueType: uint64List
	ListErpReq_ListOptIdList ListErpReq_ListOpt = 1
	// @valueType: string
	ListErpReq_ListOptName ListErpReq_ListOpt = 2
)

// Enum value maps for ListErpReq_ListOpt.
var (
	ListErpReq_ListOpt_name = map[int32]string{
		0: "ListOptNil",
		1: "ListOptIdList",
		2: "ListOptName",
	}
	ListErpReq_ListOpt_value = map[string]int32{
		"ListOptNil":    0,
		"ListOptIdList": 1,
		"ListOptName":   2,
	}
)

func (x ListErpReq_ListOpt) Enum() *ListErpReq_ListOpt {
	p := new(ListErpReq_ListOpt)
	*p = x
	return p
}

func (x ListErpReq_ListOpt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListErpReq_ListOpt) Descriptor() protoreflect.EnumDescriptor {
	return file_erp_proto_enumTypes[1].Descriptor()
}

func (ListErpReq_ListOpt) Type() protoreflect.EnumType {
	return &file_erp_proto_enumTypes[1]
}

func (x ListErpReq_ListOpt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListErpReq_ListOpt.Descriptor instead.
func (ListErpReq_ListOpt) EnumDescriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{10, 0}
}

type ModelErp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gorm: primarykey
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primarykey"`
	// @gorm: comment:'企业ID'
	CorpId uint64 `protobuf:"varint,102,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty" gorm:"comment:'企业ID'"`
	// @gorm: comment:'创建时间'
	CreatedAt uint32 `protobuf:"varint,103,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"comment:'创建时间'"`
	// @gorm: comment:'更新时间'
	UpdatedAt uint32 `protobuf:"varint,104,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"comment:'更新时间'"`
	// @gorm: comment:'删除时间'
	DeletedAt uint32 `protobuf:"varint,105,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"comment:'删除时间'"`
}

func (x *ModelErp) Reset() {
	*x = ModelErp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelErp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelErp) ProtoMessage() {}

func (x *ModelErp) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelErp.ProtoReflect.Descriptor instead.
func (*ModelErp) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{0}
}

func (x *ModelErp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelErp) GetCorpId() uint64 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *ModelErp) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelErp) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelErp) GetDeletedAt() uint32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type ModelRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gorm: primarykey
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primarykey"`
	// @gorm: comment:'企业ID'
	CorpId uint64 `protobuf:"varint,102,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty" gorm:"comment:'企业ID'"`
	// @gorm: comment:'创建时间'
	CreatedAt uint32 `protobuf:"varint,103,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"comment:'创建时间'"`
	// @gorm: comment:'更新时间'
	UpdatedAt uint32 `protobuf:"varint,104,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"comment:'更新时间'"`
	// @gorm: comment:'删除时间'
	DeletedAt uint32 `protobuf:"varint,105,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"comment:'删除时间'"`
}

func (x *ModelRole) Reset() {
	*x = ModelRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRole) ProtoMessage() {}

func (x *ModelRole) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRole.ProtoReflect.Descriptor instead.
func (*ModelRole) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{1}
}

func (x *ModelRole) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelRole) GetCorpId() uint64 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *ModelRole) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelRole) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelRole) GetDeletedAt() uint32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type CreateErpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelErp `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateErpReq) Reset() {
	*x = CreateErpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateErpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateErpReq) ProtoMessage() {}

func (x *CreateErpReq) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateErpReq.ProtoReflect.Descriptor instead.
func (*CreateErpReq) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{2}
}

func (x *CreateErpReq) GetData() *ModelErp {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateErpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelErp `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateErpRsp) Reset() {
	*x = CreateErpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateErpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateErpRsp) ProtoMessage() {}

func (x *CreateErpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateErpRsp.ProtoReflect.Descriptor instead.
func (*CreateErpRsp) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{3}
}

func (x *CreateErpRsp) GetData() *ModelErp {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateErpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelErp `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateErpReq) Reset() {
	*x = UpdateErpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateErpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateErpReq) ProtoMessage() {}

func (x *UpdateErpReq) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateErpReq.ProtoReflect.Descriptor instead.
func (*UpdateErpReq) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateErpReq) GetData() *ModelErp {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateErpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelErp `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateErpRsp) Reset() {
	*x = UpdateErpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateErpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateErpRsp) ProtoMessage() {}

func (x *UpdateErpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateErpRsp.ProtoReflect.Descriptor instead.
func (*UpdateErpRsp) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateErpRsp) GetData() *ModelErp {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteErpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteErpReq) Reset() {
	*x = DeleteErpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteErpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteErpReq) ProtoMessage() {}

func (x *DeleteErpReq) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteErpReq.ProtoReflect.Descriptor instead.
func (*DeleteErpReq) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteErpReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteErpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteErpRsp) Reset() {
	*x = DeleteErpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteErpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteErpRsp) ProtoMessage() {}

func (x *DeleteErpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteErpRsp.ProtoReflect.Descriptor instead.
func (*DeleteErpRsp) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{7}
}

type GetErpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetErpReq) Reset() {
	*x = GetErpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErpReq) ProtoMessage() {}

func (x *GetErpReq) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErpReq.ProtoReflect.Descriptor instead.
func (*GetErpReq) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{8}
}

func (x *GetErpReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetErpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelErp `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetErpRsp) Reset() {
	*x = GetErpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErpRsp) ProtoMessage() {}

func (x *GetErpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErpRsp.ProtoReflect.Descriptor instead.
func (*GetErpRsp) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{9}
}

func (x *GetErpRsp) GetData() *ModelErp {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListErpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOption *listoption.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *ListErpReq) Reset() {
	*x = ListErpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListErpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErpReq) ProtoMessage() {}

func (x *ListErpReq) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListErpReq.ProtoReflect.Descriptor instead.
func (*ListErpReq) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{10}
}

func (x *ListErpReq) GetListOption() *listoption.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type ListErpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *listoption.Paginate `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelErp          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListErpRsp) Reset() {
	*x = ListErpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListErpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErpRsp) ProtoMessage() {}

func (x *ListErpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_erp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListErpRsp.ProtoReflect.Descriptor instead.
func (*ListErpRsp) Descriptor() ([]byte, []int) {
	return file_erp_proto_rawDescGZIP(), []int{11}
}

func (x *ListErpRsp) GetPaginate() *listoption.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *ListErpRsp) GetList() []*ModelErp {
	if x != nil {
		return x.List
	}
	return nil
}

var File_erp_proto protoreflect.FileDescriptor

var file_erp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x72, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x65, 0x72, 0x70,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x6c, 0x69, 0x73, 0x74, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x08, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x45, 0x72, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x72, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x66,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x67, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x68, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x69, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x09, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x72, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x66, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x72, 0x70, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x67,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x68, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x69, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x3b, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x72,
	0x70, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x45, 0x72, 0x70, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a,
	0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x45, 0x72, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b, 0x0a,
	0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x72,
	0x70, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x45, 0x72, 0x70, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a,
	0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x45, 0x72, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02,
	0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x22, 0x24, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x45, 0x72, 0x70,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x45, 0x72, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x84, 0x01, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x0b, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x12,
	0x0e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x10, 0x02, 0x22, 0x61, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x72, 0x70, 0x52, 0x73,
	0x70, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x45, 0x72, 0x70,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x2a, 0x6a, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x72, 0x72,
	0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72, 0x70, 0x10, 0x03, 0x12, 0x13, 0x0a,
	0x0f, 0x45, 0x72, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65,
	0x10, 0x04, 0x32, 0xa4, 0x02, 0x0a, 0x03, 0x65, 0x72, 0x70, 0x12, 0x31, 0x0a, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x12, 0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x72, 0x70,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x12, 0x31, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x12, 0x11, 0x2e, 0x65, 0x72, 0x70,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x65, 0x72, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70,
	0x12, 0x31, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x72, 0x70, 0x12, 0x11, 0x2e,
	0x65, 0x72, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x72, 0x70,
	0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x45, 0x72, 0x70, 0x12, 0x0e, 0x2e,
	0x65, 0x72, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x65, 0x72, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x12, 0x2b, 0x0a,
	0x07, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x72, 0x70, 0x12, 0x0f, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x65, 0x72, 0x70, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x09, 0x44, 0x44,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x72, 0x70, 0x12, 0x0f, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x72, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x72, 0x70, 0x52, 0x73, 0x70, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x49, 0x41, 0x57, 0x65, 0x61, 0x2f, 0x65,
	0x72, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x70,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_erp_proto_rawDescOnce sync.Once
	file_erp_proto_rawDescData = file_erp_proto_rawDesc
)

func file_erp_proto_rawDescGZIP() []byte {
	file_erp_proto_rawDescOnce.Do(func() {
		file_erp_proto_rawDescData = protoimpl.X.CompressGZIP(file_erp_proto_rawDescData)
	})
	return file_erp_proto_rawDescData
}

var file_erp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_erp_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_erp_proto_goTypes = []interface{}{
	(ErrCode)(0),                  // 0: erp.ErrCode
	(ListErpReq_ListOpt)(0),       // 1: erp.ListErpReq.ListOpt
	(*ModelErp)(nil),              // 2: erp.ModelErp
	(*ModelRole)(nil),             // 3: erp.ModelRole
	(*CreateErpReq)(nil),          // 4: erp.CreateErpReq
	(*CreateErpRsp)(nil),          // 5: erp.CreateErpRsp
	(*UpdateErpReq)(nil),          // 6: erp.UpdateErpReq
	(*UpdateErpRsp)(nil),          // 7: erp.UpdateErpRsp
	(*DeleteErpReq)(nil),          // 8: erp.DeleteErpReq
	(*DeleteErpRsp)(nil),          // 9: erp.DeleteErpRsp
	(*GetErpReq)(nil),             // 10: erp.GetErpReq
	(*GetErpRsp)(nil),             // 11: erp.GetErpRsp
	(*ListErpReq)(nil),            // 12: erp.ListErpReq
	(*ListErpRsp)(nil),            // 13: erp.ListErpRsp
	(*listoption.ListOption)(nil), // 14: listoption.ListOption
	(*listoption.Paginate)(nil),   // 15: listoption.Paginate
}
var file_erp_proto_depIdxs = []int32{
	2,  // 0: erp.CreateErpReq.data:type_name -> erp.ModelErp
	2,  // 1: erp.CreateErpRsp.data:type_name -> erp.ModelErp
	2,  // 2: erp.UpdateErpReq.data:type_name -> erp.ModelErp
	2,  // 3: erp.UpdateErpRsp.data:type_name -> erp.ModelErp
	2,  // 4: erp.GetErpRsp.data:type_name -> erp.ModelErp
	14, // 5: erp.ListErpReq.list_option:type_name -> listoption.ListOption
	15, // 6: erp.ListErpRsp.paginate:type_name -> listoption.Paginate
	2,  // 7: erp.ListErpRsp.list:type_name -> erp.ModelErp
	4,  // 8: erp.erp.CreateErp:input_type -> erp.CreateErpReq
	6,  // 9: erp.erp.UpdateErp:input_type -> erp.UpdateErpReq
	8,  // 10: erp.erp.DeleteErp:input_type -> erp.DeleteErpReq
	10, // 11: erp.erp.GetErp:input_type -> erp.GetErpReq
	12, // 12: erp.erp.ListErp:input_type -> erp.ListErpReq
	12, // 13: erp.erp.DDListErp:input_type -> erp.ListErpReq
	5,  // 14: erp.erp.CreateErp:output_type -> erp.CreateErpRsp
	7,  // 15: erp.erp.UpdateErp:output_type -> erp.UpdateErpRsp
	9,  // 16: erp.erp.DeleteErp:output_type -> erp.DeleteErpRsp
	11, // 17: erp.erp.GetErp:output_type -> erp.GetErpRsp
	13, // 18: erp.erp.ListErp:output_type -> erp.ListErpRsp
	13, // 19: erp.erp.DDListErp:output_type -> erp.ListErpRsp
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_erp_proto_init() }
func file_erp_proto_init() {
	if File_erp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_erp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelErp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateErpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateErpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateErpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateErpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteErpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteErpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListErpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListErpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_erp_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_erp_proto_goTypes,
		DependencyIndexes: file_erp_proto_depIdxs,
		EnumInfos:         file_erp_proto_enumTypes,
		MessageInfos:      file_erp_proto_msgTypes,
	}.Build()
	File_erp_proto = out.File
	file_erp_proto_rawDesc = nil
	file_erp_proto_goTypes = nil
	file_erp_proto_depIdxs = nil
}
