basePath: /erp
definitions:
  erp.CreatePlanDetailReq:
    properties:
      data:
        $ref: '#/definitions/erp.ModelPlanDetail'
    type: object
  erp.CreatePlanDetailRsp:
    type: object
  erp.ListPlanDetailReq:
    properties:
      list_option:
        $ref: '#/definitions/listoption.ListOption'
    type: object
  erp.ListPlanDetailRsp:
    properties:
      accountMap:
        additionalProperties:
          $ref: '#/definitions/erp.ModelAccount'
        type: object
      list:
        items:
          $ref: '#/definitions/erp.ModelPlanDetail'
        type: array
      paginate:
        $ref: '#/definitions/listoption.Paginate'
    type: object
  erp.ListPlanReq:
    properties:
      is_export:
        type: boolean
      list_option:
        $ref: '#/definitions/listoption.ListOption'
    type: object
  erp.ListPlanRsp:
    properties:
      list:
        items:
          $ref: '#/definitions/erp.ModelPlan'
        type: array
      paginate:
        $ref: '#/definitions/listoption.Paginate'
    type: object
  erp.ModelAccount:
    properties:
      created_at:
        description: '@gorm: comment:''创建时间'''
        type: integer
      deleted_at:
        description: '@gorm: uniqueIndex:uniq_name;comment:''删除时间'''
        type: integer
      id:
        description: '@gorm: primarykey'
        type: integer
      initial_money:
        description: '@gorm: type:int(11);comment:''初期余额'''
        type: integer
      name:
        description: '@gorm: uniqueIndex:uniq_name;type:varchar(32);comment:''账户名'''
        type: string
      updated_at:
        description: '@gorm: comment:''更新时间'''
        type: integer
    type: object
  erp.ModelPlan:
    properties:
      att_name:
        description: '@gorm: type:varchar(128);not null;comment:''附件名'''
        type: string
      attachment:
        description: '@gorm: type:varchar(128);not null;comment:''附件'''
        type: string
      balance_money:
        description: '@gorm: comment:''剩余金额，单位分'''
        type: integer
      comment:
        description: '@gorm: type:varchar(64);not null;comment:''备注'''
        type: string
      created_at:
        description: '@gorm: comment:''创建时间'''
        type: integer
      customer:
        description: '@gorm: comment:客户名称'
        type: string
      deleted_at:
        description: '@gorm: comment:''删除时间'''
        type: integer
      id:
        description: '@gorm: primarykey'
        type: integer
      mark:
        description: '@gorm: type:varchar(64);not null;comment:''摘要'''
        type: string
      plan_at:
        description: '@gorm: comment:''日期'''
        type: integer
      status:
        description: |-
          Status
          @gorm: type:tinyint(1);default:0;comment:状态
        type: integer
      total_money:
        description: '@gorm: comment:''总金额，单位分'''
        type: integer
      trade_money:
        description: '@gorm: comment:''已付/已收金额，单位分'''
        type: integer
      type:
        description: Type
        type: integer
      updated_at:
        description: '@gorm: comment:''更新时间'''
        type: integer
      user_id:
        description: '@gorm: comment:''创建用户'''
        type: integer
      uuid:
        description: '@gorm: uniqueIndex:uniq_uuid;type:varchar(32);comment:''唯一ID'''
        type: string
      version:
        description: '@gorm: type:int(10);default:0;comment:版本号'
        type: integer
    type: object
  erp.ModelPlanDetail:
    properties:
      account_id:
        description: '@gorm: comment:''账户'''
        type: integer
      att_name:
        description: '@gorm: type:varchar(128);not null;comment:''附件名'''
        type: string
      attachment:
        description: '@gorm: type:varchar(128);not null;comment:''附件'''
        type: string
      comment:
        description: '@gorm: type:varchar(64);not null;comment:''备注'''
        type: string
      created_at:
        description: '@gorm: comment:创建时间'
        type: integer
      deleted_at:
        description: '@gorm: comment:删除时间'
        type: integer
      handle_by:
        description: '@gorm: type:varchar(64);not null;comment:''经手人'''
        type: string
      id:
        description: '@gorm: primarykey'
        type: integer
      mark:
        description: '@gorm: type:varchar(64);not null;comment:''摘要'''
        type: string
      plan_at:
        description: '@gorm: comment:''日期'''
        type: integer
      plan_id:
        type: integer
      trade_money:
        description: '@gorm: comment:交易金额，单位分'
        type: integer
      updated_at:
        description: '@gorm: comment:更新时间'
        type: integer
      user_id:
        description: '@gorm: comment:''创建用户'''
        type: integer
      uuid:
        description: '@gorm: uniqueIndex:uniq_uuid;type:varchar(32);comment:''唯一ID'''
        type: string
    type: object
  listoption.ListOption:
    properties:
      limit:
        description: '@desc: 分页的每页字段长度'
        type: integer
      offset:
        description: '@desc: 需要获取的索引开始位置'
        type: integer
      offset_token:
        description: '@desc: 需要获取的索引开始位置标记'
        type: string
      options:
        description: "@desc: 搜索过滤逻辑，不支持逻辑或\n\n\toptions内部是逻辑与关系，暂不支持逻辑或；尽量避免复杂的过滤逻辑，后台不好分页\n\n@ignore:
          all"
        items:
          $ref: '#/definitions/listoption.ListOption_Option'
        type: array
      skip_count:
        description: '@desc: = true 时, 就算 offset = 0 也不要 count'
        type: boolean
    type: object
  listoption.ListOption_Option:
    properties:
      type:
        description: '@desc: 类型，各业务定义的type'
        type: integer
      value:
        description: '@desc: 参数，只支持1个参数，参数实际类型和意义由type决定'
        type: string
    type: object
  listoption.Paginate:
    properties:
      has_more:
        description: '@desc: 是否有更多数据，新字段，老接口不一定会填，要跟后端开发沟通好'
        type: boolean
      limit:
        description: '@desc: 每页结果数'
        type: integer
      next_offset_token:
        description: '@desc: 下次索引开始位置标记,为空标示没有下一个了'
        type: string
      offset:
        description: '@desc: 当前获取到的第一个的索引位置'
        type: integer
      total:
        description: '@desc: 总页数'
        type: integer
    type: object
host: localhost:5050
info:
  contact: {}
  description: ErpServer API
  title: Swagger Example API
  version: "1.0"
paths:
  /erp/CreatePlanDetail:
    post:
      consumes:
      - application/json
      description: 创建明细
      parameters:
      - description: JSON入参
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/erp.CreatePlanDetailReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/erp.CreatePlanDetailRsp'
      summary: 创建明细
      tags:
      - 应收应付
  /erp/ListPlan:
    post:
      consumes:
      - application/json
      description: 应收应付列表
      parameters:
      - description: options:[{type:1,value:'1'(1应付，2应收))},{type:2,value:'客户名称'},{type:3,value:'摘要'},{type:4,value:'1694957121,1694957127'}]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/erp.ListPlanReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/erp.ListPlanRsp'
      summary: 应收应付列表
      tags:
      - 应收应付
  /erp/ListPlanDetail:
    post:
      consumes:
      - application/json
      description: 明细列表
      parameters:
      - description: 'options: [{type:1,value:''plan_id'')}]'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/erp.ListPlanDetailReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/erp.ListPlanDetailRsp'
      summary: 明细列表
      tags:
      - 应收应付
swagger: "2.0"
